title: Streaming Accent Translation System
description: Authors: Yuanzhe Chen, Ming Tu, Tang Li, Xin Li, Qiuqiang Kong, Jiaxin Li, Zhichao Wang, Qiao Tian, Yuping Wang, Yuxuan Wang
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
